// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadAttachment(arg1) {
  return window['go']['main']['App']['DownloadAttachment'](arg1);
}

export function LoadUnstamped() {
  return window['go']['main']['App']['LoadUnstamped']();
}

export function SignIn() {
  return window['go']['main']['App']['SignIn']();
}

export function UploadStamped(arg1, arg2) {
  return window['go']['main']['App']['UploadStamped'](arg1, arg2);
}
