// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {api} from '../models';

export function DownloadAttachment(arg1:number):Promise<string>;

export function LoadUnstamped():Promise<Array<main.Oath>>;

export function SignIn():Promise<api.UserInfo>;

export function UploadStamped(arg1:number,arg2:string):Promise<void>;
